language: node_js

node_js:
  - "8"
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn build

script:
  - yarn test:coverage

after_script:
  - yarn coverage
